// Generated by CoffeeScript 1.6.2
(function() {
  var HOST, PORT, client, net;

  net = require('net');

  HOST = '192.168.11.133';

  PORT = 6969;

  client = new net.Socket();

  client.connect(PORT, HOST, function() {
    console.log("CONNECTED TO: " + HOST + ":" + PORT);
    return client.write("I am Chuck Norris!");
  });

  client.on('data', function(data) {
    console.log("DATA: " + data);
    return client.destroy();
  });

  client.on('close', function() {
    return console.log("Connection closed");
  });

}).call(this);
