// Generated by CoffeeScript 1.6.2
(function() {
  var HOST, PORT, app, net;

  net = require('net');

  HOST = '192.168.11.133';

  PORT = 6969;

  app = net.createServer(function(sc) {
    console.log("CONNECTION: " + sc.remoteAddress + ": " + sc.remotePort);
    sc.on('data', function(data) {
      console.log("DATA: " + sc.remoteAddress + ": " + data);
      return sc.write("You said " + data);
    });
    return sc.on('close', function(data) {
      return console.log("CLOSED: " + sc.remoteAddress + ": " + sc.remotePort);
    });
  });

  app.listen(PORT, HOST, function() {
    return console.log("Server listening on " + HOST + ":" + PORT);
  });

}).call(this);
