// Generated by CoffeeScript 1.6.2
(function() {
  var eldest, grade, student, students, _i, _len;

  grade = function(student) {
    if (student.excellentWork) {
      return "A+";
    } else if (student.okayStuff) {
      if (student.triedHard) {
        return "B";
      } else {
        return "B-";
      }
    } else {
      return "C";
    }
  };

  eldest = 24 > 21 ? "Liz" : "Ike";

  students = [
    {
      name: "David",
      excellentWork: true
    }, {
      name: "Holln",
      okayStuff: true
    }, {
      name: "John",
      okayStuff: true,
      triedHard: true
    }, {
      name: "Sanji"
    }
  ];

  for (_i = 0, _len = students.length; _i < _len; _i++) {
    student = students[_i];
    student.score = grade(student);
    console.log("" + student.name + "'s score: " + student.score);
  }

}).call(this);
