// Generated by CoffeeScript 1.6.2
(function() {
  var ignition;

  ignition = process.argv[2];

  if (ignition === "true") {
    (function() {
      return console.log("launch");
    })();
  } else {
    (function() {
      return console.log("not launch");
    })();
  }

}).call(this);
