// Generated by CoffeeScript 1.6.2
(function() {
  var footprints, solipsism, speed, str;

  if ((typeof mind !== "undefined" && mind !== null) && (typeof world === "undefined" || world === null)) {
    solipsism = true;
  }

  speed = 0;

  if (speed == null) {
    speed = 15;
  }

  str = '';

  str || (str = 'haha');

  footprints = typeof yeti !== "undefined" && yeti !== null ? yeti : "bear";

  console.log(solipsism, speed, str, footprints);

}).call(this);
