// Generated by CoffeeScript 1.6.2
(function() {
  var zip, _ref;

  zip = typeof lottery !== "undefined" && lottery !== null ? typeof lottery.drawWinner === "function" ? (_ref = lottery.drawWinner().address) != null ? _ref.zipcode : void 0 : void 0 : void 0;

}).call(this);
