// Generated by CoffeeScript 1.6.2
(function() {
  var Person, close, contents, open, person, tag, _i, _ref,
    __slice = [].slice;

  tag = "<impossible>";

  _ref = tag.split(""), open = _ref[0], contents = 3 <= _ref.length ? __slice.call(_ref, 1, _i = _ref.length - 1) : (_i = 1, []), close = _ref[_i++];

  console.log(contents);

  Person = (function() {
    function Person(options) {
      this.name = options.name, this.age = options.age, this.height = options.height;
    }

    return Person;

  })();

  person = new Person({
    name: "David",
    age: 24,
    height: 180
  });

  console.log(person);

}).call(this);
