// Generated by CoffeeScript 1.6.2
(function() {
  var a, b, users;

  users = [
    {
      name: 'alec',
      age: 10
    }, {
      name: 'bert',
      age: 16
    }
  ];

  a = [
    {
      name: 'alec',
      age: 10
    }, {
      name: 'bert',
      age: 16
    }
  ];

  b = [
    {
      item1: {
        name: 'value1'
      }
    }, {
      item2: {
        name: 'value2'
      }
    }
  ];

}).call(this);
